// Mock data for local prototype

import { User, Property, MatchRequest, Message } from './types'

export const mockUsers: User[] = [
  {
    id: 'user-1',
    email: 'sarah@example.com',
    password: 'password123',
    name: 'Sarah Johnson',
    role: 'seeker',
    bio: 'Software engineer looking for a peaceful place to call home. I love cooking and weekend hikes.',
    age: 28,
    occupation: 'Software Engineer',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
    preferences: {
      cleanliness: 5,
      noiseTolerance: 2,
      socialLevel: 3,
      pets: 'love',
      smoking: 'no',
      overnight_guests: 2,
      shared_expenses: 3,
    },
    createdAt: '2025-01-01T10:00:00Z',
  },
  {
    id: 'user-2',
    email: 'mike@example.com',
    password: 'password123',
    name: 'Mike Chen',
    role: 'landlord',
    bio: 'Property owner seeking responsible tenants for my beautiful downtown apartment.',
    age: 45,
    occupation: 'Real Estate Investor',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    preferences: {
      cleanliness: 4,
      noiseTolerance: 3,
      socialLevel: 3,
      pets: 'ok',
      smoking: 'no',
      overnight_guests: 3,
      shared_expenses: 2,
    },
    createdAt: '2025-01-02T10:00:00Z',
  },
  {
    id: 'user-3',
    email: 'emma@example.com',
    password: 'password123',
    name: 'Emma Williams',
    role: 'seeker',
    bio: 'Graduate student and yoga instructor. Looking for a zen space with good vibes.',
    age: 25,
    occupation: 'Graduate Student',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
    preferences: {
      cleanliness: 4,
      noiseTolerance: 2,
      socialLevel: 4,
      pets: 'love',
      smoking: 'no',
      overnight_guests: 3,
      shared_expenses: 4,
    },
    createdAt: '2025-01-03T10:00:00Z',
  },
  {
    id: 'user-4',
    email: 'david@example.com',
    password: 'password123',
    name: 'David Martinez',
    role: 'landlord',
    bio: 'Landlord with multiple properties in the city. Looking for long-term tenants.',
    age: 52,
    occupation: 'Property Manager',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
    preferences: {
      cleanliness: 5,
      noiseTolerance: 2,
      socialLevel: 2,
      pets: 'no',
      smoking: 'no',
      overnight_guests: 2,
      shared_expenses: 1,
    },
    createdAt: '2025-01-04T10:00:00Z',
  },
  {
    id: 'user-5',
    email: 'lisa@example.com',
    password: 'password123',
    name: 'Lisa Anderson',
    role: 'landlord',
    bio: 'Artist and homeowner renting out my spare rooms. Love creative, respectful people.',
    age: 38,
    occupation: 'Artist',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop',
    preferences: {
      cleanliness: 3,
      noiseTolerance: 4,
      socialLevel: 5,
      pets: 'love',
      smoking: 'occasional',
      overnight_guests: 4,
      shared_expenses: 4,
    },
    createdAt: '2025-01-05T10:00:00Z',
  },
]

export const mockProperties: Property[] = [
  {
    id: 'prop-1',
    landlordId: 'user-2',
    title: 'Modern Appartement Hasselt Centrum',
    description: 'Ruim 2-slaapkamer appartement in het hart van Hasselt centrum. Op loopafstand van de Grote Markt, winkels, restaurants en openbaar vervoer. Recent gerenoveerd met moderne apparatuur en hardhouten vloeren.',
    price: 950,
    city: 'Hasselt',
    address: 'Grote Markt 15, 3500 Hasselt',
    latitude: 50.9320,
    longitude: 5.3385,
    bedrooms: 2,
    bathrooms: 1,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop',
    ],
    amenities: ['WiFi', 'Dishwasher', 'Laundry', 'Parking', 'Pet-friendly'],
    preferences: {
      cleanliness: 4,
      noiseTolerance: 3,
      socialLevel: 3,
      pets: 'ok',
      smoking: 'no',
      overnight_guests: 3,
      shared_expenses: 2,
    },
    availableFrom: '2025-02-01',
    createdAt: '2025-01-06T10:00:00Z',
  },
  {
    id: 'prop-2',
    landlordId: 'user-4',
    title: 'Gezellige Studio Kapelstraat',
    description: 'Rustige studio in de karakteristieke Kapelstraat. Perfect voor iemand die waarde hecht aan rust en authenticiteit. Geen huisdieren of roken toegestaan.',
    price: 650,
    city: 'Hasselt',
    address: 'Kapelstraat 89, 3500 Hasselt',
    latitude: 50.9290,
    longitude: 5.3400,
    bedrooms: 1,
    bathrooms: 1,
    images: [
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&h=600&fit=crop',
    ],
    amenities: ['WiFi', 'Heating', 'Garden access'],
    preferences: {
      cleanliness: 5,
      noiseTolerance: 1,
      socialLevel: 2,
      pets: 'no',
      smoking: 'no',
      overnight_guests: 1,
      shared_expenses: 1,
    },
    availableFrom: '2025-02-15',
    createdAt: '2025-01-07T10:00:00Z',
  },
  {
    id: 'prop-3',
    landlordId: 'user-5',
    title: 'Ruime Woning Kuringen',
    description: 'Grote gezinswoning in de rustige wijk Kuringen. Ruime tuin, meerdere slaapkamers en moderne voorzieningen. Ideaal voor gezinnen of WG. Huisdieren welkom!',
    price: 1100,
    city: 'Hasselt',
    address: 'Herkenrodesingel 45, 3500 Hasselt (Kuringen)',
    latitude: 50.9550,
    longitude: 5.2800,
    bedrooms: 3,
    bathrooms: 2,
    images: [
      'https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1531835551805-16d864c8d311?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&h=600&fit=crop',
    ],
    amenities: ['WiFi', 'Natural light', 'Garden', 'Pet-friendly', 'Parking'],
    preferences: {
      cleanliness: 3,
      noiseTolerance: 4,
      socialLevel: 5,
      pets: 'love',
      smoking: 'occasional',
      overnight_guests: 5,
      shared_expenses: 4,
    },
    availableFrom: '2025-03-01',
    createdAt: '2025-01-08T10:00:00Z',
  },
  {
    id: 'prop-4',
    landlordId: 'user-2',
    title: 'Kunstenaarsloods Genk',
    description: 'Voormalige industriële ruimte omgebouwd tot moderne woonloft in het creatieve hart van Genk. Hoge plafonds, veel lichtinval en artistieke sfeer. Ideaal voor creatievelingen!',
    price: 850,
    city: 'Genk',
    address: 'C-Mine 10, 3600 Genk',
    latitude: 50.9650,
    longitude: 5.4200,
    bedrooms: 1,
    bathrooms: 1,
    images: [
      'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1556020685-ae41abfc9365?w=800&h=600&fit=crop',
    ],
    amenities: ['WiFi', 'Art studio', 'Parking', 'Industrial style'],
    preferences: {
      cleanliness: 4,
      noiseTolerance: 2,
      socialLevel: 3,
      pets: 'ok',
      smoking: 'no',
      overnight_guests: 2,
      shared_expenses: 3,
    },
    availableFrom: '2025-02-01',
    createdAt: '2025-01-09T10:00:00Z',
  },
  {
    id: 'prop-5',
    landlordId: 'user-4',
    title: 'Rustig Appartement Sint-Truiden',
    description: 'Prachtig appartement in historisch centrum van Sint-Truiden. Nabij de Grote Markt en bloesemroute. Ideaal voor professionals die rust en authenticiteit zoeken.',
    price: 750,
    city: 'Sint-Truiden',
    address: 'Grote Markt 8, 3800 Sint-Truiden',
    latitude: 50.8850,
    longitude: 5.2100,
    bedrooms: 2,
    bathrooms: 1,
    images: [
      'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1574643156929-51fa098b0394?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop',
    ],
    amenities: ['WiFi', 'Dishwasher', 'Historic building', 'City center'],
    preferences: {
      cleanliness: 5,
      noiseTolerance: 2,
      socialLevel: 2,
      pets: 'no',
      smoking: 'no',
      overnight_guests: 2,
      shared_expenses: 1,
    },
    availableFrom: '2025-02-01',
    createdAt: '2025-01-10T10:00:00Z',
  },
  {
    id: 'prop-6',
    landlordId: 'user-5',
    title: 'Familiehuis Diepenbeek',
    description: 'Charmante gezinswoning in groene wijk van Diepenbeek. Nabij Universiteit Hasselt en scholen. Ruime tuin en rustige buurt. Zeer huisdiervriendelijk!',
    price: 1050,
    city: 'Diepenbeek',
    address: 'Winterslagstraat 23, 3590 Diepenbeek',
    latitude: 50.9100,
    longitude: 5.1950,
    bedrooms: 3,
    bathrooms: 2,
    images: [
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1506059612708-99d6c258160e?w=800&h=600&fit=crop',
    ],
    amenities: ['WiFi', 'Garden', 'Parking', 'Pet-friendly', 'Near university'],
    preferences: {
      cleanliness: 3,
      noiseTolerance: 4,
      socialLevel: 4,
      pets: 'love',
      smoking: 'occasional',
      overnight_guests: 4,
      shared_expenses: 3,
    },
    availableFrom: '2025-03-15',
    createdAt: '2025-01-11T10:00:00Z',
  },
]

export const mockMatchRequests: MatchRequest[] = [
  {
    id: 'match-1',
    seekerId: 'user-1',
    propertyId: 'prop-1',
    landlordId: 'user-2',
    message: 'Hi! I love your apartment. I\'m a quiet professional and would take great care of the place.',
    status: 'pending',
    compatibilityScore: 85,
    createdAt: '2025-01-15T10:00:00Z',
    updatedAt: '2025-01-15T10:00:00Z',
  },
  {
    id: 'match-2',
    seekerId: 'user-3',
    propertyId: 'prop-3',
    landlordId: 'user-5',
    message: 'Your loft looks amazing! I\'m a yoga instructor and artist, and I think we\'d vibe really well.',
    status: 'accepted',
    compatibilityScore: 92,
    createdAt: '2025-01-14T10:00:00Z',
    updatedAt: '2025-01-16T10:00:00Z',
  },
]

export const mockMessages: Message[] = [
  {
    id: 'msg-1',
    senderId: 'user-2',
    receiverId: 'user-1',
    matchRequestId: 'match-1',
    content: 'Thanks for your interest! When would you like to schedule a viewing?',
    read: false,
    createdAt: '2025-01-15T14:00:00Z',
  },
  {
    id: 'msg-2',
    senderId: 'user-5',
    receiverId: 'user-3',
    matchRequestId: 'match-2',
    content: 'I\'d love to have you! Your profile looks great. Let\'s set up a time to meet.',
    read: true,
    createdAt: '2025-01-16T09:00:00Z',
  },
  {
    id: 'msg-3',
    senderId: 'user-3',
    receiverId: 'user-5',
    matchRequestId: 'match-2',
    content: 'That sounds perfect! I\'m free this weekend if that works for you?',
    read: true,
    createdAt: '2025-01-16T10:30:00Z',
  },
]
